services:
  dotnet-app:
    build:
      dockerfile: Dockerfile
    container_name: "performance-test-api-app"
    ports:
      - "5235:8080"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5G"
  dotnet-test:
    depends_on:
      - dotnet-app
    build:
      dockerfile: Dockerfile-IntegrationTest
    container_name: "performance-test-api-test"
    environment:
      - SUT=http://performance-test-api-app