services:
  dotnet-test:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: performance-test-api-test
    network_mode: "host"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SUT=http://localhost:31001
    command: [ "dotnet", "test", "--logger:trx", "--logger:html" ]
