services:
  dotnet-test:
    build:
      dockerfile: Dockerfile-IntegrationTest
    network_mode: "host"
    container_name: "performance-test-api-test"
    environment:
      - SUT=http://localhost:31001