apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-test-api-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: performance-test-api-app
    spec:
      containers:
      - name: performance-test-api
        image: performance-test-api-image
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
  selector:
    matchLabels:
      app: performance-test-api-app