apiVersion: v1
kind: Service
metadata:
  name: performance-test-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5235
      targetPort: 8080
  selector:
    app: performance-test-api