apiVersion: v1
kind: Service
metadata:
  name: performance-test-api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: performance-test-api-app